#!/bin/bash

echo "raspi-config安装脚本"
if ! [ -x "$(command -v raspi-config)" ]; then
  echo 'raspi-config is not installed.' >&2
  echo '现在开始安装...' >&2
  latest=$(curl https://archive.raspberrypi.org/debian/pool/main/r/raspi-config/ | egrep -o "raspi-config_[0-9]{8}_all.deb" |sort -rn)
  url="https://archive.raspberrypi.org/debian/pool/main/r/raspi-config/"
  cd /tmp
  wget $url${latest: 0 :29}
  sudo apt-get install -y lua5.1  libatopology2 libfftw3-single3 libsamplerate0 alsa-utils whiptail parted initramfs-tools
  sudo dpkg -i ${latest: 0 :29}
  echo "install completed"
  rm -f ${latest: 0 :29}
  exit 1
else
  echo "raspi-config已经安装"
fi

