#!/bin/bash
# 安装vcgencmd

# 64位系统
if [ arch == "aarch64"]; then
  echo `arch` 
  git clone https://github.com/raspberrypi/userland.git 
  cd userland
  ./buildme --aarch64
  echo "/opt/vc/lib" >> /etc/ld.so.conf
  ldconfig
  exit
fi

# 32位系统
if [ ! -d "/opt/vc" ]; then
  cd /opt
  svn checkout https://github.com/raspberrypi/firmware/trunk/opt/vc
  echo "/opt/vc/lib" >> /etc/ld.so.conf
  ldconfig
  echo "install vcgencmd comleted!"
else
  echo "vcgencmd 已经安装"  
fi
